import { Card } from '../../components/ui/Card';
import { Table, TableRow, TableCell } from '../../components/ui/Table';
import { Badge } from '../../components/ui/Badge';
import { FileText, Download, Calendar } from 'lucide-react';

const myRx = [
  { id: 'RX-8921', date: 'Today, 10:45 AM', patient: 'Sarah Jenkins', meds: 'Sumatriptan 50mg (9 tabs)', status: 'Active' },
  { id: 'RX-8920', date: 'Yesterday', patient: 'Will Byers', meds: 'Amoxicillin 500mg, Ibuprofen 400mg', status: 'Active' },
  { id: 'RX-8845', date: 'Oct 10, 2023', patient: 'Mike Ross', meds: 'Lisinopril 10mg (30 days)', status: 'Expired' },
];

export function DoctorPrescriptionsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
           <FileText className="text-green-500" /> Prescriptions History
        </h1>
        <p className="text-sm text-slate-500 mt-1">Review all prescriptions generated by you.</p>
      </div>

      <Card className="shadow-sm border border-slate-100 !p-0 overflow-hidden">
        <Table headers={['Rx ID & Date', 'Patient Name', 'Medications Prescribed', 'Status', 'Actions']}>
          {myRx.map((rx) => (
            <TableRow key={rx.id}>
              <TableCell>
                <div className="font-semibold text-slate-900">{rx.id}</div>
                <div className="text-xs text-slate-500 flex items-center gap-1 mt-0.5"><Calendar size={12}/> {rx.date}</div>
              </TableCell>
              <TableCell className="font-medium text-slate-700">{rx.patient}</TableCell>
              <TableCell className="text-slate-600 max-w-xs">{rx.meds}</TableCell>
              <TableCell>
                <Badge variant={rx.status === 'Active' ? 'success' : 'default'}>{rx.status}</Badge>
              </TableCell>
              <TableCell>
                 <button className="text-green-600 hover:text-green-700 hover:bg-green-50 p-2 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium">
                    <Download size={16} /> PDF
                 </button>
              </TableCell>
            </TableRow>
          ))}
        </Table>
      </Card>
    </div>
  );
}
